# Site settings
title: Kvirin.Me
email: filip@kvirin.me
description: > # this means to ignore newlines until "baseurl:"
  Личный сайт и блог Филипа Квирина. Здесь собраны материалы и рассуждения на
  разнообразные темы: литература, общество, жизнь, самоанализ, наблюдения,
  творчество, известные люди, программирование, технологии, будущее и прочее.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kvirin.me/" # the base hostname & protocol for your site
twitter_username: kvirin
github_username:  kvirin

# Build settings
markdown: kramdown
